/**
 * Seed the database with realistic dropshipping products.
 */
import pg from './node_modules/pg/lib/index.js'
const { Client } = pg

const DATABASE_URL = process.env.DATABASE_URL
if (!DATABASE_URL) { console.error('DATABASE_URL required'); process.exit(1) }

const client = new Client({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } })

function makeTrendData(months = 12, direction = 'up') {
  const base = 30 + Math.floor(Math.random() * 40)
  return Array.from({ length: months }, (_, i) => {
    const date = new Date()
    date.setMonth(date.getMonth() - (months - i))
    let vol
    if (direction === 'up') vol = Math.round(base * (1 + i * 0.08 + (Math.random() - 0.4) * 0.1))
    else if (direction === 'down') vol = Math.round(base * Math.max(0.3, 1 - i * 0.05 + (Math.random() - 0.5) * 0.05))
    else vol = Math.round(base * (1 + (Math.random() - 0.5) * 0.15))
    vol = Math.max(5, Math.min(100, vol))
    return { date: date.toISOString().slice(0, 10), searchVolume: vol, salesIndex: Math.max(5, Math.round(vol * (0.5 + Math.random()))) }
  })
}

const PRODUCTS = [
  { name: 'Portable LED Ring Light 10 inch', description: 'Professional LED ring light with adjustable colour temperature (3000K-6000K), 3 lighting modes, and flexible 360° phone holder. Perfect for TikTok, YouTube, Instagram content creation and video calls. Includes phone clip, USB cable, and carry bag.', category: 'Electronics Accessories', tags: ['ring light','selfie','streaming','content creator','LED'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099512994137', source_price_usd: 4.50, source_min_order_qty: 30, source_shipping_estimate_usd: 2.80, source_image_url: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400', best_sell_platform: 'amazon', amazon_asin: 'B08GLZMQ3L', avg_sell_price_usd: 26.99, estimated_monthly_sales: 3200, sales_rank: 45, review_count: 8420, avg_review_score: 4.3, is_trending: true, trend: 'up' },
  { name: 'Magnetic Phone Car Mount Dashboard', description: 'Universal magnetic car phone holder with 6 strong neodymium magnets, 360° rotation, and dual adhesive base. Compatible with all smartphones. Ultra-slim design. Dashboard and windscreen mounting options.', category: 'Auto Accessories', tags: ['car mount','magnetic','phone holder','dashboard','GPS'], source_platform: 'aliexpress', source_url: 'https://www.aliexpress.com/item/3256804971234567.html', source_price_usd: 1.80, source_min_order_qty: 50, source_shipping_estimate_usd: 1.50, source_image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 14.99, estimated_monthly_sales: 5800, sales_rank: 12, review_count: 22000, avg_review_score: 4.1, is_trending: false, trend: 'flat' },
  { name: 'Stainless Steel Insulated Water Bottle 1L', description: 'Double-wall vacuum insulated stainless steel water bottle. Keeps drinks cold for 24 hours and hot for 12 hours. BPA-free, leak-proof lid with carry loop. Fits standard cup holders.', category: 'Sports & Outdoors', tags: ['water bottle','insulated','stainless steel','gym','hiking'], source_platform: 'alibaba', source_url: 'https://www.alibaba.com/product-detail/1L-Insulated-Water-Bottle_1600123456789.html', source_price_usd: 3.20, source_min_order_qty: 100, source_shipping_estimate_usd: 4.50, source_image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 22.99, estimated_monthly_sales: 4100, sales_rank: 28, review_count: 15600, avg_review_score: 4.5, is_trending: true, trend: 'up' },
  { name: 'Cable Management Box Desktop Organiser', description: 'Wooden cable management box to hide power strips and messy cables. Holds up to 6 power outlets. Removable divider, ventilation slots prevent overheating. Available in white, black, and natural wood.', category: 'Home & Garden', tags: ['cable management','desk organiser','home office','cable box'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513012345', source_price_usd: 5.80, source_min_order_qty: 20, source_shipping_estimate_usd: 5.50, source_image_url: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 29.99, estimated_monthly_sales: 2600, sales_rank: 67, review_count: 5200, avg_review_score: 4.4, is_trending: true, trend: 'up' },
  { name: 'Silicone Pet Food Bowl Non-Slip 2-Pack', description: 'Collapsible silicone pet bowls, food-grade BPA-free material. Non-slip base prevents sliding. Dishwasher safe. Perfect for travel, camping, hiking with pets. Suitable for dogs and cats.', category: 'Pet Supplies', tags: ['pet bowl','dog bowl','cat bowl','travel','silicone'], source_platform: 'aliexpress', source_url: 'https://www.aliexpress.com/item/3256805123456789.html', source_price_usd: 2.10, source_min_order_qty: 50, source_shipping_estimate_usd: 2.00, source_image_url: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 12.99, estimated_monthly_sales: 1800, sales_rank: 89, review_count: 3400, avg_review_score: 4.6, is_trending: false, trend: 'flat' },
  { name: 'Posture Corrector Back Support Brace', description: 'Adjustable posture corrector for men and women. Lightweight breathable material, invisible under clothing. Corrects slouching and back pain. Adjustable shoulder straps fit chest sizes 28-48 inches.', category: 'Beauty & Health', tags: ['posture','back support','pain relief','office','health'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513098765', source_price_usd: 3.90, source_min_order_qty: 30, source_shipping_estimate_usd: 2.50, source_image_url: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 19.99, estimated_monthly_sales: 2200, sales_rank: 156, review_count: 6800, avg_review_score: 4.0, is_trending: true, trend: 'up' },
  { name: 'Foldable Laptop Stand Adjustable Aluminium', description: 'Portable aluminium laptop stand with 6 adjustable height levels. Compatible with laptops 10-17 inches, tablets, and MacBooks. Improves posture and airflow. Non-slip rubber feet. Weight: 310g.', category: 'Office Supplies', tags: ['laptop stand','ergonomic','aluminium','portable','work from home'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513156789', source_price_usd: 6.50, source_min_order_qty: 20, source_shipping_estimate_usd: 3.50, source_image_url: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 34.99, estimated_monthly_sales: 3500, sales_rank: 34, review_count: 11200, avg_review_score: 4.4, is_trending: true, trend: 'up' },
  { name: 'Resistance Bands Set 5-Pack', description: 'Premium fabric resistance bands for legs and glutes. 5 resistance levels from 15lb to 55lb. Non-slip anti-snap design. Includes carrying bag and workout guide. Suitable for yoga, pilates, home workouts.', category: 'Sports & Outdoors', tags: ['resistance bands','fitness','workout','gym','yoga'], source_platform: 'aliexpress', source_url: 'https://www.aliexpress.com/item/3256804567890123.html', source_price_usd: 2.80, source_min_order_qty: 50, source_shipping_estimate_usd: 2.00, source_image_url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 16.99, estimated_monthly_sales: 4800, sales_rank: 23, review_count: 18900, avg_review_score: 4.3, is_trending: true, trend: 'up' },
  { name: 'Reusable Beeswax Food Wraps 6-Pack', description: 'Eco-friendly reusable food wraps made from organic cotton and beeswax. Replaces plastic cling film. Keeps food fresh longer. 3 sizes. Machine washable at 30°C. Zero waste kitchen essential.', category: 'Kitchen', tags: ['eco-friendly','beeswax','food wrap','sustainable','zero waste'], source_platform: 'alibaba', source_url: 'https://www.alibaba.com/product-detail/beeswax-food-wraps_1600345678901.html', source_price_usd: 3.50, source_min_order_qty: 100, source_shipping_estimate_usd: 3.00, source_image_url: 'https://images.unsplash.com/photo-1542621334-a254cf47733d?w=400', best_sell_platform: 'etsy', avg_sell_price_usd: 18.99, estimated_monthly_sales: 900, sales_rank: 345, review_count: 2100, avg_review_score: 4.7, is_trending: true, trend: 'up' },
  { name: 'LED Strip Lights 5m USB Powered RGB', description: 'USB LED strip lights 5 metres, 300 LEDs, 16 colours + remote control. Waterproof IP65, cuttable every 3 LEDs. Perfect for bedroom, gaming setup, TV backlight, kitchen under-cabinet lighting.', category: 'Home & Garden', tags: ['LED lights','strip lights','gaming','bedroom','decor'], source_platform: 'aliexpress', source_url: 'https://www.aliexpress.com/item/3256803456789012.html', source_price_usd: 3.80, source_min_order_qty: 50, source_shipping_estimate_usd: 2.50, source_image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 15.99, estimated_monthly_sales: 6200, sales_rank: 8, review_count: 28000, avg_review_score: 4.2, is_trending: true, trend: 'up' },
  { name: 'Electric Facial Massager Microcurrent Device', description: 'Microcurrent facial lifting device with 5 intensity levels. EMS stimulation lifts facial muscles, reduces fine lines. Includes LED light therapy (red + blue). USB rechargeable, auto-off timer.', category: 'Beauty & Health', tags: ['facial massager','microcurrent','anti-aging','skincare','EMS'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513547890', source_price_usd: 8.90, source_min_order_qty: 20, source_shipping_estimate_usd: 2.50, source_image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 39.99, estimated_monthly_sales: 2800, sales_rank: 78, review_count: 6700, avg_review_score: 4.2, is_trending: true, trend: 'up' },
  { name: 'Smart Plant Pot Self-Watering 6 inch', description: 'Self-watering planter with water level indicator. Inner pot with drainage, outer reservoir holds water for up to 3 weeks. Suitable for herbs, small plants, and succulents. Modern minimalist design.', category: 'Home & Garden', tags: ['plant pot','self-watering','indoor plants','gardening','home decor'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513468901', source_price_usd: 3.10, source_min_order_qty: 30, source_shipping_estimate_usd: 3.50, source_image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400', best_sell_platform: 'etsy', avg_sell_price_usd: 16.99, estimated_monthly_sales: 1200, sales_rank: 234, review_count: 2800, avg_review_score: 4.6, is_trending: true, trend: 'up' },
  { name: 'Waterproof Phone Pouch Universal IPX8', description: 'Universal waterproof phone pouch IPX8 certified. Clear front and back, fits phones up to 7 inches. Adjustable neck lanyard and armband. Perfect for beach, swimming, kayaking. Touch screen compatible.', category: 'Sports & Outdoors', tags: ['waterproof','phone pouch','beach','swimming','summer'], source_platform: 'aliexpress', source_url: 'https://www.aliexpress.com/item/3256802345678901.html', source_price_usd: 1.50, source_min_order_qty: 100, source_shipping_estimate_usd: 1.50, source_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 9.99, estimated_monthly_sales: 4400, sales_rank: 89, review_count: 12400, avg_review_score: 4.0, is_trending: true, trend: 'up' },
  { name: 'Acrylic Nail Art Kit Professional 120pc', description: 'Complete professional nail art kit with 120 pieces. Includes acrylic nail tips, UV gel, base coat, top coat, nail file, buffer, brushes, and nail art tools. Salon quality at home.', category: 'Beauty & Health', tags: ['nail art','acrylic nails','gel nails','beauty','DIY'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513390123', source_price_usd: 7.50, source_min_order_qty: 20, source_shipping_estimate_usd: 3.00, source_image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 29.99, estimated_monthly_sales: 3100, sales_rank: 56, review_count: 9200, avg_review_score: 4.1, is_trending: true, trend: 'up' },
  { name: 'Bamboo Cutting Board Set of 3', description: 'Premium bamboo cutting board set with juice groove and handle. 3 sizes: small, medium, large. Natural antibacterial properties. Dishwasher safe, eco-friendly. Suitable for meat, vegetables, bread.', category: 'Kitchen', tags: ['cutting board','bamboo','kitchen','eco-friendly','cooking'], source_platform: 'alibaba', source_url: 'https://www.alibaba.com/product-detail/bamboo-cutting-board_1600234567890.html', source_price_usd: 4.20, source_min_order_qty: 50, source_shipping_estimate_usd: 6.00, source_image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 24.99, estimated_monthly_sales: 1900, sales_rank: 203, review_count: 4100, avg_review_score: 4.5, is_trending: false, trend: 'flat' },
  { name: 'Foam Puzzle Floor Mat 36-Piece Set', description: 'Interlocking foam floor mat set, 36 tiles each 30x30cm. Creates 3.2 sqm of cushioned play area. EVA foam, non-toxic, BPA-free. Perfect for children\'s playroom, home gym, yoga.', category: 'Toys & Games', tags: ['foam mat','play mat','children','gym mat','interlocking'], source_platform: 'alibaba', source_url: 'https://www.alibaba.com/product-detail/foam-puzzle-mat_1600567890123.html', source_price_usd: 9.50, source_min_order_qty: 20, source_shipping_estimate_usd: 12.00, source_image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 34.99, estimated_monthly_sales: 2100, sales_rank: 123, review_count: 5400, avg_review_score: 4.4, is_trending: false, trend: 'flat' },
  { name: 'Car Seat Back Organiser Kick Mat', description: 'Premium car seat back organiser and kick mat. 8 pockets including tablet pocket for 10-inch devices. Waterproof, scratch-resistant. Prevents dirt and scuff marks. Universal fit.', category: 'Auto Accessories', tags: ['car organiser','kick mat','back seat','storage','children'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513234567', source_price_usd: 5.20, source_min_order_qty: 30, source_shipping_estimate_usd: 4.00, source_image_url: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 21.99, estimated_monthly_sales: 1600, sales_rank: 278, review_count: 4300, avg_review_score: 4.2, is_trending: false, trend: 'flat' },
  { name: 'Silk Sleep Mask Contoured Eye Cover', description: '100% natural mulberry silk sleep mask. Adjustable head strap, ultra-soft eye cover with contoured design. Blocks 100% light. Includes earplugs and carry pouch. For travel and shift workers.', category: 'Beauty & Health', tags: ['sleep mask','silk','eye mask','travel','sleep'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513312345', source_price_usd: 2.20, source_min_order_qty: 50, source_shipping_estimate_usd: 1.80, source_image_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 12.99, estimated_monthly_sales: 2400, sales_rank: 145, review_count: 7800, avg_review_score: 4.4, is_trending: false, trend: 'flat' },
  { name: 'Wooden Desk Organiser 7-Compartment', description: 'Multi-functional bamboo desk organiser with 7 compartments for pens, scissors, tape, stapler. Includes 2 small drawers. Natural bamboo finish for any home office. Dimensions: 28x18x12cm.', category: 'Office Supplies', tags: ['desk organiser','bamboo','office','stationary','storage'], source_platform: 'alibaba', source_url: 'https://www.alibaba.com/product-detail/wooden-desk-organiser_1600456789012.html', source_price_usd: 5.50, source_min_order_qty: 50, source_shipping_estimate_usd: 7.00, source_image_url: 'https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 24.99, estimated_monthly_sales: 1400, sales_rank: 312, review_count: 3600, avg_review_score: 4.5, is_trending: false, trend: 'flat' },
  { name: 'Portable Blender USB Rechargeable 380ml', description: 'Personal mini blender for smoothies, shakes, and protein drinks. 380ml BPA-free bottle. USB-C rechargeable, 6 stainless steel blades. Includes travel lid and carry bag. 5-minute charge for 15 blends.', category: 'Kitchen', tags: ['blender','smoothie','portable','USB','fitness'], source_platform: 'temu', source_url: 'https://www.temu.com/goods.html?goods_id=601099513600001', source_price_usd: 8.20, source_min_order_qty: 30, source_shipping_estimate_usd: 3.00, source_image_url: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400', best_sell_platform: 'amazon', avg_sell_price_usd: 32.99, estimated_monthly_sales: 2900, sales_rank: 67, review_count: 7800, avg_review_score: 4.2, is_trending: true, trend: 'up' },
]

async function seed() {
  await client.connect()
  console.log('Connected to database')
  let count = 0

  for (const p of PRODUCTS) {
    const { trend, ...data } = p
    const trendData = makeTrendData(12, trend)

    const existing = await client.query('SELECT id FROM products WHERE name = $1', [p.name])
    if (existing.rows.length > 0) {
      console.log(`  Skip (exists): ${p.name.slice(0, 45)}`)
      continue
    }

    await client.query(`
      INSERT INTO products (
        name, description, category, tags,
        source_platform, source_url, source_price_usd, source_min_order_qty,
        source_shipping_estimate_usd, source_image_url,
        best_sell_platform, amazon_asin, avg_sell_price_usd,
        estimated_monthly_sales, sales_rank, review_count, avg_review_score,
        trend_data, is_trending, scraped_at, last_refreshed
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,NOW(),NOW()
      )
    `, [
      data.name, data.description, data.category, data.tags,
      data.source_platform, data.source_url, data.source_price_usd, data.source_min_order_qty,
      data.source_shipping_estimate_usd, data.source_image_url,
      data.best_sell_platform, data.amazon_asin || null, data.avg_sell_price_usd,
      data.estimated_monthly_sales, data.sales_rank, data.review_count, data.avg_review_score,
      JSON.stringify(trendData), data.is_trending,
    ])
    count++
    console.log(`  ✅ ${data.name.slice(0, 50)}`)
  }

  await client.end()
  console.log(`\n✅ Seeded ${count} products`)
}

seed().catch(err => { console.error('Seed failed:', err.message); process.exit(1) })
